# TODO: Alterar SERVICE_NAME pelo nome do serviço. Ex: rml-srv-*
spring:
  application:
    name: rml-srv-SERVICE_NAME

server:
  # TODO: Definir porta única para cada serviço
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
