# TODO: Substituir SERVICE_NAME e a porta pelo valor real
apiVersion: v1
kind: Service
metadata:
  name: rml-srv-SERVICE_NAME
  namespace: sovarais
spec:
  selector:
    app: rml-srv-SERVICE_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
